CREATE DATABASE IF NOT EXISTS `django_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'django'@'%' IDENTIFIED BY 'django123456';
GRANT ALL PRIVILEGES ON `django_db`.* TO 'django'@'%';
FLUSH PRIVILEGES;
